### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by shomarov** [tikibeni/ot-harjoitustyo#1]
### Koodikatselmointi
_Ladattu 28.04 12:00_

Sovelluksen yleisilme on hyvä. Ulkonäköön on selvästi panostettu ja ux on hyvä.

- Luokat jaettu pakkauksiin, myös testiluokat.
- Pakkaukset, luokat, metodit, attribuutit, parametrit ja muuttujat nimetty selkeästi ja johdonmukaisesti.
- Unit testit kattavia ja toimivia. TestCourseDao ja TestPlanDao olisi kannattanut nimetä CourseDaoTest:ksi ja vastaavasti PlanDaoTest:ksi jotta yhdenmukaisuus säilyisi.

Katsotaan sitten luokkien sisäinen laatu.

#### CourseFileDao:

- metodi initialize ei tarvitse parametria String courseFile koska asetat sen konstruktorissa oliomuuttujaksi.

- konstruktorin ilme olisi paljon parempi ja luettavampi jos se näyttäisi seuraavalta:

```
public CourseFileDao(String courseFile, String courseInfo) throws Exception {
        this.courses = new ArrayList<>();
        this.courseFile = courseFile;
        try {
            initialize();
        } catch (FileNotFoundException e) {
            createCourseFile();
        }
    }
```

Eli siirretään catch lausekeen alla oleva koodi omaan metodiin.

Sama juttu initialize() metodissa. Se ajaa monta asiaa joita voi hyvin eriyttää omiini metodeihin. Esimerkiksi alla oleva if (!line.equals("")) {} ehto; sen voi siirtää omaan addCourse(String line) metodiin.

#### PlanFileDao:

Sama kun edellisessä. Konstruktori refaktoroidaan pienemmäksi ja eriytetään muu koodi omiin metodeihin.

```
public PlanFileDao(String file, CourseDao courses) throws Exception {
        plans = new ArrayList<>();
        this.file = file;
	init();
    }
```

Mikä on muuten CourseDao courses pointti tossa konstruktorissa?

#### Course, Plan:
- luokat suoraviivaiset, ei paljon sanottavaa, muuttujat ja metodit hyvin nimettyjä.

#### PlanService:
- luokka näyttää hyvältä. Metodit pienet, selkeät ja hyvin nimettyjä.

#### Testit:
- testejä paljon
- testikattavuus 74%, erinomaista!
- testit lyhyet, selkeät ja ajavat yhtä asiaa.

Hyvää työtä!

**Comment by tikibeni** [comment]
Suuret kiitokset ajatuksella tehdystä katselmoinnista! Sain tehtyä koodista huomattavasti loogisempaa tämän ansiosta!
